// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type GetUsersResponses = {
    /**
     * Success
     */
    200: string;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetApiV1TransactionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/transactions/';
};

export type GetApiV1TransactionsErrors = {
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1TransactionsError = GetApiV1TransactionsErrors[keyof GetApiV1TransactionsErrors];

export type GetApiV1TransactionsResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: Array<{
            id: string;
            userId: string | null;
            commitmentId: string;
            transactionType: 'stake' | 'payout' | 'forfeit' | 'rake' | 'refund';
            status: 'pending' | 'succeeded' | 'failed';
            stripeCustomerId: string | null;
            stripeTransactionId: string;
            amount: number;
            createdAt: string;
        }>;
    };
};

export type GetApiV1TransactionsResponse = GetApiV1TransactionsResponses[keyof GetApiV1TransactionsResponses];

export type GetApiV1TransactionsIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/transactions/:id';
};

export type GetApiV1TransactionsIdErrors = {
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1TransactionsIdError = GetApiV1TransactionsIdErrors[keyof GetApiV1TransactionsIdErrors];

export type GetApiV1TransactionsIdResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            userId: string | null;
            commitmentId: string;
            transactionType: 'stake' | 'payout' | 'forfeit' | 'rake' | 'refund';
            status: 'pending' | 'succeeded' | 'failed';
            stripeCustomerId: string | null;
            stripeTransactionId: string;
            amount: number;
            createdAt: string;
        };
    };
};

export type GetApiV1TransactionsIdResponse = GetApiV1TransactionsIdResponses[keyof GetApiV1TransactionsIdResponses];

export type GetApiV1CommitmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/commitments/';
};

export type GetApiV1CommitmentsErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1CommitmentsError = GetApiV1CommitmentsErrors[keyof GetApiV1CommitmentsErrors];

export type GetApiV1CommitmentsResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: Array<{
            id: string;
            type: 'walk' | 'run' | 'sleep' | 'screentime';
            frequency: 'three_times_a_week' | 'four_times_a_week' | 'five_times_a_week' | 'six_times_a_week' | 'seven_times_a_week';
            duration: 'one_weeks' | 'two_weeks' | 'three_weeks' | 'four_weeks';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            startDate: string;
            endDate: string | null;
            stakeAmount: number;
            lockedBonusAmount: number;
            status: 'pending_payment' | 'payment_processing' | 'active' | 'completed' | 'forfeited' | 'cancelled' | 'cancelled_refunded' | 'refund_pending';
            gracePeriodEndsAt: string;
        }>;
    };
};

export type GetApiV1CommitmentsResponse = GetApiV1CommitmentsResponses[keyof GetApiV1CommitmentsResponses];

export type PostApiV1CommitmentsData = {
    /**
     * Request body
     */
    body?: {
        type: 'walk' | 'run' | 'sleep' | 'screentime';
        frequency: 'three_times_a_week' | 'four_times_a_week' | 'five_times_a_week' | 'six_times_a_week' | 'seven_times_a_week';
        duration: 'one_weeks' | 'two_weeks' | 'three_weeks' | 'four_weeks';
        sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
        stakeAmount: number;
        lockedBonusAmount?: number;
    };
    path?: never;
    query?: never;
    url: '/api/v1/commitments/';
};

export type PostApiV1CommitmentsResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            type: 'walk' | 'run' | 'sleep' | 'screentime';
            frequency: 'three_times_a_week' | 'four_times_a_week' | 'five_times_a_week' | 'six_times_a_week' | 'seven_times_a_week';
            duration: 'one_weeks' | 'two_weeks' | 'three_weeks' | 'four_weeks';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            startDate: string;
            endDate: string | null;
            stakeAmount: number;
            lockedBonusAmount: number;
            status: 'pending_payment' | 'payment_processing' | 'active' | 'completed' | 'forfeited' | 'cancelled' | 'cancelled_refunded' | 'refund_pending';
            gracePeriodEndsAt: string;
        };
    };
};

export type PostApiV1CommitmentsResponse = PostApiV1CommitmentsResponses[keyof PostApiV1CommitmentsResponses];

export type GetApiV1CommitmentsActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/commitments/active';
};

export type GetApiV1CommitmentsActiveResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: Array<{
            id: string;
            type: 'walk' | 'run' | 'sleep' | 'screentime';
            frequency: 'three_times_a_week' | 'four_times_a_week' | 'five_times_a_week' | 'six_times_a_week' | 'seven_times_a_week';
            duration: 'one_weeks' | 'two_weeks' | 'three_weeks' | 'four_weeks';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            startDate: string;
            endDate: string | null;
            stakeAmount: number;
            lockedBonusAmount: number;
            status: 'pending_payment' | 'payment_processing' | 'active' | 'completed' | 'forfeited' | 'cancelled' | 'cancelled_refunded' | 'refund_pending';
            gracePeriodEndsAt: string;
        }>;
    };
};

export type GetApiV1CommitmentsActiveResponse = GetApiV1CommitmentsActiveResponses[keyof GetApiV1CommitmentsActiveResponses];

export type DeleteApiV1CommitmentsIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitments/:id';
};

export type DeleteApiV1CommitmentsIdResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: number;
    };
};

export type DeleteApiV1CommitmentsIdResponse = DeleteApiV1CommitmentsIdResponses[keyof DeleteApiV1CommitmentsIdResponses];

export type GetApiV1CommitmentsIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitments/:id';
};

export type GetApiV1CommitmentsIdErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1CommitmentsIdError = GetApiV1CommitmentsIdErrors[keyof GetApiV1CommitmentsIdErrors];

export type GetApiV1CommitmentsIdResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            type: 'walk' | 'run' | 'sleep' | 'screentime';
            frequency: 'three_times_a_week' | 'four_times_a_week' | 'five_times_a_week' | 'six_times_a_week' | 'seven_times_a_week';
            duration: 'one_weeks' | 'two_weeks' | 'three_weeks' | 'four_weeks';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            startDate: string;
            endDate: string | null;
            stakeAmount: number;
            lockedBonusAmount: number;
            status: 'pending_payment' | 'payment_processing' | 'active' | 'completed' | 'forfeited' | 'cancelled' | 'cancelled_refunded' | 'refund_pending';
            gracePeriodEndsAt: string;
        };
    };
};

export type GetApiV1CommitmentsIdResponse = GetApiV1CommitmentsIdResponses[keyof GetApiV1CommitmentsIdResponses];

export type PatchApiV1CommitmentsIdData = {
    /**
     * Request body
     */
    body?: {
        status?: 'pending_payment' | 'payment_processing' | 'active' | 'completed' | 'forfeited' | 'cancelled' | 'cancelled_refunded' | 'refund_pending';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitments/:id';
};

export type PatchApiV1CommitmentsIdResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            type: 'walk' | 'run' | 'sleep' | 'screentime';
            frequency: 'three_times_a_week' | 'four_times_a_week' | 'five_times_a_week' | 'six_times_a_week' | 'seven_times_a_week';
            duration: 'one_weeks' | 'two_weeks' | 'three_weeks' | 'four_weeks';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            startDate: string;
            endDate: string | null;
            stakeAmount: number;
            lockedBonusAmount: number;
            status: 'pending_payment' | 'payment_processing' | 'active' | 'completed' | 'forfeited' | 'cancelled' | 'cancelled_refunded' | 'refund_pending';
            gracePeriodEndsAt: string;
        };
    };
};

export type PatchApiV1CommitmentsIdResponse = PatchApiV1CommitmentsIdResponses[keyof PatchApiV1CommitmentsIdResponses];

export type GetApiV1CommitmentsIdCancelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitments/:id/cancel';
};

export type GetApiV1CommitmentsIdCancelResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            cancellable: boolean;
            message?: string;
            refundable: boolean;
            forfeitAmount: number;
            stakeAmount: number;
            gracePeriodEndsAt: string | null;
        };
    };
};

export type GetApiV1CommitmentsIdCancelResponse = GetApiV1CommitmentsIdCancelResponses[keyof GetApiV1CommitmentsIdCancelResponses];

export type PostApiV1CommitmentsIdCancelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitments/:id/cancel';
};

export type PostApiV1CommitmentsIdCancelResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            refunded: boolean;
            forfeitedAmount: number;
            status: 'pending_payment' | 'payment_processing' | 'active' | 'completed' | 'forfeited' | 'cancelled' | 'cancelled_refunded' | 'refund_pending';
        };
    };
};

export type PostApiV1CommitmentsIdCancelResponse = PostApiV1CommitmentsIdCancelResponses[keyof PostApiV1CommitmentsIdCancelResponses];

export type GetApiV1CommitmentsIdProgressData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitments/:id/progress';
};

export type GetApiV1CommitmentsIdProgressErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1CommitmentsIdProgressError = GetApiV1CommitmentsIdProgressErrors[keyof GetApiV1CommitmentsIdProgressErrors];

export type GetApiV1CommitmentsIdProgressResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            commitmentId: string;
            totalRequired: number;
            completedSessions: number;
            currentWeek: number;
            totalWeeks: number;
            sessionsThisWeek: number;
            requiredPerWeek: number;
        };
    };
};

export type GetApiV1CommitmentsIdProgressResponse = GetApiV1CommitmentsIdProgressResponses[keyof GetApiV1CommitmentsIdProgressResponses];

export type GetApiV1CommitmentsIdSessionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitments/:id/sessions';
};

export type GetApiV1CommitmentsIdSessionsErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1CommitmentsIdSessionsError = GetApiV1CommitmentsIdSessionsErrors[keyof GetApiV1CommitmentsIdSessionsErrors];

export type GetApiV1CommitmentsIdSessionsResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: Array<{
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        }>;
    };
};

export type GetApiV1CommitmentsIdSessionsResponse = GetApiV1CommitmentsIdSessionsResponses[keyof GetApiV1CommitmentsIdSessionsResponses];

export type GetApiV1CommitmentSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/commitment-sessions/';
};

export type GetApiV1CommitmentSessionsErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1CommitmentSessionsError = GetApiV1CommitmentSessionsErrors[keyof GetApiV1CommitmentSessionsErrors];

export type GetApiV1CommitmentSessionsResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: Array<{
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        }>;
    };
};

export type GetApiV1CommitmentSessionsResponse = GetApiV1CommitmentSessionsResponses[keyof GetApiV1CommitmentSessionsResponses];

export type PostApiV1CommitmentSessionsData = {
    /**
     * Request body
     */
    body?: {
        commitmentId: string;
        timezone: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/commitment-sessions/';
};

export type PostApiV1CommitmentSessionsErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Conflict
     */
    409: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1CommitmentSessionsError = PostApiV1CommitmentSessionsErrors[keyof PostApiV1CommitmentSessionsErrors];

export type PostApiV1CommitmentSessionsResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        };
    };
    /**
     * Created
     */
    201: {
        success: true;
        data: {
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        };
    };
};

export type PostApiV1CommitmentSessionsResponse = PostApiV1CommitmentSessionsResponses[keyof PostApiV1CommitmentSessionsResponses];

export type GetApiV1CommitmentSessionsIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitment-sessions/:id';
};

export type GetApiV1CommitmentSessionsIdErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1CommitmentSessionsIdError = GetApiV1CommitmentSessionsIdErrors[keyof GetApiV1CommitmentSessionsIdErrors];

export type GetApiV1CommitmentSessionsIdResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        };
    };
};

export type GetApiV1CommitmentSessionsIdResponse = GetApiV1CommitmentSessionsIdResponses[keyof GetApiV1CommitmentSessionsIdResponses];

export type PostApiV1CommitmentSessionsIdCompleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitment-sessions/:id/complete';
};

export type PostApiV1CommitmentSessionsIdCompleteErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Conflict
     */
    409: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1CommitmentSessionsIdCompleteError = PostApiV1CommitmentSessionsIdCompleteErrors[keyof PostApiV1CommitmentSessionsIdCompleteErrors];

export type PostApiV1CommitmentSessionsIdCompleteResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        };
    };
};

export type PostApiV1CommitmentSessionsIdCompleteResponse = PostApiV1CommitmentSessionsIdCompleteResponses[keyof PostApiV1CommitmentSessionsIdCompleteResponses];

export type PostApiV1CommitmentSessionsIdCancelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitment-sessions/:id/cancel';
};

export type PostApiV1CommitmentSessionsIdCancelErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Conflict
     */
    409: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1CommitmentSessionsIdCancelError = PostApiV1CommitmentSessionsIdCancelErrors[keyof PostApiV1CommitmentSessionsIdCancelErrors];

export type PostApiV1CommitmentSessionsIdCancelResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        };
    };
};

export type PostApiV1CommitmentSessionsIdCancelResponse = PostApiV1CommitmentSessionsIdCancelResponses[keyof PostApiV1CommitmentSessionsIdCancelResponses];

export type PostApiV1CommitmentSessionsIdPauseData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitment-sessions/:id/pause';
};

export type PostApiV1CommitmentSessionsIdPauseErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Conflict
     */
    409: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1CommitmentSessionsIdPauseError = PostApiV1CommitmentSessionsIdPauseErrors[keyof PostApiV1CommitmentSessionsIdPauseErrors];

export type PostApiV1CommitmentSessionsIdPauseResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        };
    };
};

export type PostApiV1CommitmentSessionsIdPauseResponse = PostApiV1CommitmentSessionsIdPauseResponses[keyof PostApiV1CommitmentSessionsIdPauseResponses];

export type PostApiV1CommitmentSessionsIdResumeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitment-sessions/:id/resume';
};

export type PostApiV1CommitmentSessionsIdResumeErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Conflict
     */
    409: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1CommitmentSessionsIdResumeError = PostApiV1CommitmentSessionsIdResumeErrors[keyof PostApiV1CommitmentSessionsIdResumeErrors];

export type PostApiV1CommitmentSessionsIdResumeResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            userId: string;
            commitmentId: string;
            startDate: string;
            endDate: string | null;
            createdAt: string;
            completedAt: string | null;
            timezone: string;
            countingDay: string;
            sessionDuration: number;
            sessionStatus: 'not_started' | 'in_progress' | 'paused' | 'completed' | 'cancelled';
            verificationStatus: 'not_started' | 'pending' | 'failed' | 'succeeded';
            sessionGoal: 'steps' | 'miles' | 'screen_time' | 'sleep_time';
            actualValue: number | null;
            flaggedForReview: boolean;
            fraudDetected: boolean;
            reviewNotes: string | null;
        };
    };
};

export type PostApiV1CommitmentSessionsIdResumeResponse = PostApiV1CommitmentSessionsIdResumeResponses[keyof PostApiV1CommitmentSessionsIdResumeResponses];

export type PostApiV1CommitmentSessionsIdVerifyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitment-sessions/:id/verify';
};

export type PostApiV1CommitmentSessionsIdVerifyErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Conflict
     */
    409: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1CommitmentSessionsIdVerifyError = PostApiV1CommitmentSessionsIdVerifyErrors[keyof PostApiV1CommitmentSessionsIdVerifyErrors];

export type PostApiV1CommitmentSessionsIdVerifyResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: string;
    };
    /**
     * Response
     */
    202: {
        success: true;
        data: string;
    };
};

export type PostApiV1CommitmentSessionsIdVerifyResponse = PostApiV1CommitmentSessionsIdVerifyResponses[keyof PostApiV1CommitmentSessionsIdVerifyResponses];

export type GetApiV1CommitmentSessionsIdSamplesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitment-sessions/:id/samples';
};

export type GetApiV1CommitmentSessionsIdSamplesErrors = {
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1CommitmentSessionsIdSamplesError = GetApiV1CommitmentSessionsIdSamplesErrors[keyof GetApiV1CommitmentSessionsIdSamplesErrors];

export type GetApiV1CommitmentSessionsIdSamplesResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            motionSamples: Array<{
                id: string;
                commitmentSessionId: string;
                capturedAt: string;
                intervalMs: number | null;
                accelX: number | null;
                accelY: number | null;
                accelZ: number | null;
                accelGX: number | null;
                accelGY: number | null;
                accelGZ: number | null;
                rotAlpha: number | null;
                rotBeta: number | null;
                rotGamma: number | null;
                rotRateAlpha: number | null;
                rotRateBeta: number | null;
                rotRateGamma: number | null;
                orientation: number | null;
            }>;
            gpsSamples: Array<{
                id: string;
                commitmentSessionId: string;
                capturedAt: string;
                lat: number;
                lng: number;
                speedMps: number | null;
                headingDeg: number | null;
                horizAcc: number | null;
            }>;
            pedometerSamples: Array<{
                id: string;
                commitmentSessionId: string;
                capturedAt: string;
                steps: number;
            }>;
        };
    };
};

export type GetApiV1CommitmentSessionsIdSamplesResponse = GetApiV1CommitmentSessionsIdSamplesResponses[keyof GetApiV1CommitmentSessionsIdSamplesResponses];

export type PostApiV1CommitmentSessionsIdSamplesData = {
    /**
     * Request body
     */
    body?: {
        motionSamples?: Array<{
            capturedAt: string | null;
            intervalMs?: number | null;
            accelX?: number | null;
            accelY?: number | null;
            accelZ?: number | null;
            accelGX?: number | null;
            accelGY?: number | null;
            accelGZ?: number | null;
            rotAlpha?: number | null;
            rotBeta?: number | null;
            rotGamma?: number | null;
            rotRateAlpha?: number | null;
            rotRateBeta?: number | null;
            rotRateGamma?: number | null;
            orientation?: number | null;
        }>;
        gpsSamples?: Array<{
            capturedAt: string | null;
            lat: number;
            lng: number;
            speedMps?: number | null;
            headingDeg?: number | null;
            horizAcc?: number | null;
        }>;
        pedometerSamples?: Array<{
            capturedAt: string | null;
            steps: number;
        }>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/commitment-sessions/:id/samples';
};

export type PostApiV1CommitmentSessionsIdSamplesErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Forbidden
     */
    403: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Not Found
     */
    404: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1CommitmentSessionsIdSamplesError = PostApiV1CommitmentSessionsIdSamplesErrors[keyof PostApiV1CommitmentSessionsIdSamplesErrors];

export type PostApiV1CommitmentSessionsIdSamplesResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            motionSamplesInserted: number;
            gpsSamplesInserted: number;
            pedometerSamplesInserted: number;
        };
    };
    /**
     * Created
     */
    201: {
        success: true;
        data: {
            motionSamplesInserted: number;
            gpsSamplesInserted: number;
            pedometerSamplesInserted: number;
        };
    };
};

export type PostApiV1CommitmentSessionsIdSamplesResponse = PostApiV1CommitmentSessionsIdSamplesResponses[keyof PostApiV1CommitmentSessionsIdSamplesResponses];

export type PostApiV1PaymentsData = {
    /**
     * Request body
     */
    body?: {
        name?: string;
        phone?: string;
        email?: string;
        metadata?: {
            [key: string]: string;
        };
        amount: number;
        currency: string;
        paymentMethodId: string;
        commitmentId: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/payments/';
};

export type PostApiV1PaymentsErrors = {
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1PaymentsError = PostApiV1PaymentsErrors[keyof PostApiV1PaymentsErrors];

export type PostApiV1PaymentsResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            paymentIntentId: string;
            clientSecret: string;
            customerSessionClientSecret: string;
            customerId: string;
            publishableKey: string;
        };
    };
};

export type PostApiV1PaymentsResponse = PostApiV1PaymentsResponses[keyof PostApiV1PaymentsResponses];

export type PostApiV1PaymentsConfirmData = {
    /**
     * Request body
     */
    body?: {
        paymentIntentId: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/payments/confirm';
};

export type PostApiV1PaymentsConfirmErrors = {
    /**
     * Bad Request
     */
    400: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostApiV1PaymentsConfirmError = PostApiV1PaymentsConfirmErrors[keyof PostApiV1PaymentsConfirmErrors];

export type PostApiV1PaymentsConfirmResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            status: string;
        };
    };
};

export type PostApiV1PaymentsConfirmResponse = PostApiV1PaymentsConfirmResponses[keyof PostApiV1PaymentsConfirmResponses];

export type GetApiV1PoolData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pool/';
};

export type GetApiV1PoolErrors = {
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type GetApiV1PoolError = GetApiV1PoolErrors[keyof GetApiV1PoolErrors];

export type GetApiV1PoolResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            id: string;
            stakesHeld: number;
            balance: number;
            totalRakeCollected: number;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type GetApiV1PoolResponse = GetApiV1PoolResponses[keyof GetApiV1PoolResponses];

export type PostWebhookPaymentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhook/payments';
};

export type PostCronForfeitExpiredData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cron/forfeit-expired';
};

export type PostCronForfeitExpiredErrors = {
    /**
     * Unauthorized
     */
    401: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: false;
        statusCode: number;
        name: string;
        message: string;
        detail?: unknown;
    };
};

export type PostCronForfeitExpiredError = PostCronForfeitExpiredErrors[keyof PostCronForfeitExpiredErrors];

export type PostCronForfeitExpiredResponses = {
    /**
     * Success
     */
    200: {
        success: true;
        data: {
            forfeitedCount: number;
            commitments: Array<{
                commitmentId: string;
                userId: string;
                stakeAmount: number;
                sessionsCompleted: number;
                sessionsRequired: number;
            }>;
        };
    };
};

export type PostCronForfeitExpiredResponse = PostCronForfeitExpiredResponses[keyof PostCronForfeitExpiredResponses];
