// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zGetUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetUsersResponse = z.string();

export const zGetApiV1TransactionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1TransactionsResponse = z.object({
    success: z.literal(true),
    data: z.array(z.object({
        id: z.uuid(),
        userId: z.union([
            z.uuid(),
            z.null()
        ]),
        commitmentId: z.uuid(),
        transactionType: z.enum([
            'stake',
            'payout',
            'forfeit',
            'rake',
            'refund'
        ]),
        status: z.enum([
            'pending',
            'succeeded',
            'failed'
        ]),
        stripeCustomerId: z.union([
            z.string(),
            z.null()
        ]),
        stripeTransactionId: z.string(),
        amount: z.int().gte(-9007199254740991).lte(9007199254740991),
        createdAt: z.iso.datetime()
    }))
});

export const zGetApiV1TransactionsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1TransactionsIdResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        userId: z.union([
            z.uuid(),
            z.null()
        ]),
        commitmentId: z.uuid(),
        transactionType: z.enum([
            'stake',
            'payout',
            'forfeit',
            'rake',
            'refund'
        ]),
        status: z.enum([
            'pending',
            'succeeded',
            'failed'
        ]),
        stripeCustomerId: z.union([
            z.string(),
            z.null()
        ]),
        stripeTransactionId: z.string(),
        amount: z.int().gte(-9007199254740991).lte(9007199254740991),
        createdAt: z.iso.datetime()
    })
});

export const zGetApiV1CommitmentsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentsResponse = z.object({
    success: z.literal(true),
    data: z.array(z.object({
        id: z.uuid(),
        type: z.enum([
            'walk',
            'run',
            'sleep',
            'screentime'
        ]),
        frequency: z.enum([
            'three_times_a_week',
            'four_times_a_week',
            'five_times_a_week',
            'six_times_a_week',
            'seven_times_a_week'
        ]),
        duration: z.enum([
            'one_weeks',
            'two_weeks',
            'three_weeks',
            'four_weeks'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        stakeAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        lockedBonusAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending_payment',
            'payment_processing',
            'active',
            'completed',
            'forfeited',
            'cancelled',
            'cancelled_refunded',
            'refund_pending'
        ]),
        gracePeriodEndsAt: z.iso.datetime()
    }))
});

export const zPostApiV1CommitmentsData = z.object({
    body: z.optional(z.object({
        type: z.enum([
            'walk',
            'run',
            'sleep',
            'screentime'
        ]),
        frequency: z.enum([
            'three_times_a_week',
            'four_times_a_week',
            'five_times_a_week',
            'six_times_a_week',
            'seven_times_a_week'
        ]),
        duration: z.enum([
            'one_weeks',
            'two_weeks',
            'three_weeks',
            'four_weeks'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        stakeAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        lockedBonusAmount: z.optional(z.int().gte(-9007199254740991).lte(9007199254740991))
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostApiV1CommitmentsResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        type: z.enum([
            'walk',
            'run',
            'sleep',
            'screentime'
        ]),
        frequency: z.enum([
            'three_times_a_week',
            'four_times_a_week',
            'five_times_a_week',
            'six_times_a_week',
            'seven_times_a_week'
        ]),
        duration: z.enum([
            'one_weeks',
            'two_weeks',
            'three_weeks',
            'four_weeks'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        stakeAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        lockedBonusAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending_payment',
            'payment_processing',
            'active',
            'completed',
            'forfeited',
            'cancelled',
            'cancelled_refunded',
            'refund_pending'
        ]),
        gracePeriodEndsAt: z.iso.datetime()
    })
});

export const zGetApiV1CommitmentsActiveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentsActiveResponse = z.object({
    success: z.literal(true),
    data: z.array(z.object({
        id: z.uuid(),
        type: z.enum([
            'walk',
            'run',
            'sleep',
            'screentime'
        ]),
        frequency: z.enum([
            'three_times_a_week',
            'four_times_a_week',
            'five_times_a_week',
            'six_times_a_week',
            'seven_times_a_week'
        ]),
        duration: z.enum([
            'one_weeks',
            'two_weeks',
            'three_weeks',
            'four_weeks'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        stakeAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        lockedBonusAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending_payment',
            'payment_processing',
            'active',
            'completed',
            'forfeited',
            'cancelled',
            'cancelled_refunded',
            'refund_pending'
        ]),
        gracePeriodEndsAt: z.iso.datetime()
    }))
});

export const zDeleteApiV1CommitmentsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zDeleteApiV1CommitmentsIdResponse = z.object({
    success: z.literal(true),
    data: z.number()
});

export const zGetApiV1CommitmentsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentsIdResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        type: z.enum([
            'walk',
            'run',
            'sleep',
            'screentime'
        ]),
        frequency: z.enum([
            'three_times_a_week',
            'four_times_a_week',
            'five_times_a_week',
            'six_times_a_week',
            'seven_times_a_week'
        ]),
        duration: z.enum([
            'one_weeks',
            'two_weeks',
            'three_weeks',
            'four_weeks'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        stakeAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        lockedBonusAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending_payment',
            'payment_processing',
            'active',
            'completed',
            'forfeited',
            'cancelled',
            'cancelled_refunded',
            'refund_pending'
        ]),
        gracePeriodEndsAt: z.iso.datetime()
    })
});

export const zPatchApiV1CommitmentsIdData = z.object({
    body: z.optional(z.object({
        status: z.optional(z.enum([
            'pending_payment',
            'payment_processing',
            'active',
            'completed',
            'forfeited',
            'cancelled',
            'cancelled_refunded',
            'refund_pending'
        ]))
    })),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPatchApiV1CommitmentsIdResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        type: z.enum([
            'walk',
            'run',
            'sleep',
            'screentime'
        ]),
        frequency: z.enum([
            'three_times_a_week',
            'four_times_a_week',
            'five_times_a_week',
            'six_times_a_week',
            'seven_times_a_week'
        ]),
        duration: z.enum([
            'one_weeks',
            'two_weeks',
            'three_weeks',
            'four_weeks'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        stakeAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        lockedBonusAmount: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending_payment',
            'payment_processing',
            'active',
            'completed',
            'forfeited',
            'cancelled',
            'cancelled_refunded',
            'refund_pending'
        ]),
        gracePeriodEndsAt: z.iso.datetime()
    })
});

export const zGetApiV1CommitmentsIdCancelData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentsIdCancelResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        cancellable: z.boolean(),
        message: z.optional(z.string()),
        refundable: z.boolean(),
        forfeitAmount: z.number(),
        stakeAmount: z.number(),
        gracePeriodEndsAt: z.union([
            z.iso.datetime(),
            z.null()
        ])
    })
});

export const zPostApiV1CommitmentsIdCancelData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostApiV1CommitmentsIdCancelResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        refunded: z.boolean(),
        forfeitedAmount: z.number(),
        status: z.enum([
            'pending_payment',
            'payment_processing',
            'active',
            'completed',
            'forfeited',
            'cancelled',
            'cancelled_refunded',
            'refund_pending'
        ])
    })
});

export const zGetApiV1CommitmentsIdProgressData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentsIdProgressResponse = z.object({
    success: z.literal(true),
    data: z.object({
        commitmentId: z.uuid(),
        totalRequired: z.number(),
        completedSessions: z.number(),
        currentWeek: z.number(),
        totalWeeks: z.number(),
        sessionsThisWeek: z.number(),
        requiredPerWeek: z.number()
    })
});

export const zGetApiV1CommitmentsIdSessionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentsIdSessionsResponse = z.object({
    success: z.literal(true),
    data: z.array(z.object({
        id: z.uuid(),
        userId: z.uuid(),
        commitmentId: z.uuid(),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        createdAt: z.iso.datetime(),
        completedAt: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        timezone: z.string(),
        countingDay: z.string(),
        sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
        sessionStatus: z.enum([
            'not_started',
            'in_progress',
            'paused',
            'completed',
            'cancelled'
        ]),
        verificationStatus: z.enum([
            'not_started',
            'pending',
            'failed',
            'succeeded'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        actualValue: z.union([
            z.number().gte(-140737488355328).lte(140737488355327),
            z.null()
        ]),
        flaggedForReview: z.boolean(),
        fraudDetected: z.boolean(),
        reviewNotes: z.union([
            z.string(),
            z.null()
        ])
    }))
});

export const zGetApiV1CommitmentSessionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentSessionsResponse = z.object({
    success: z.literal(true),
    data: z.array(z.object({
        id: z.uuid(),
        userId: z.uuid(),
        commitmentId: z.uuid(),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        createdAt: z.iso.datetime(),
        completedAt: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        timezone: z.string(),
        countingDay: z.string(),
        sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
        sessionStatus: z.enum([
            'not_started',
            'in_progress',
            'paused',
            'completed',
            'cancelled'
        ]),
        verificationStatus: z.enum([
            'not_started',
            'pending',
            'failed',
            'succeeded'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        actualValue: z.union([
            z.number().gte(-140737488355328).lte(140737488355327),
            z.null()
        ]),
        flaggedForReview: z.boolean(),
        fraudDetected: z.boolean(),
        reviewNotes: z.union([
            z.string(),
            z.null()
        ])
    }))
});

export const zPostApiV1CommitmentSessionsData = z.object({
    body: z.optional(z.object({
        commitmentId: z.uuid(),
        timezone: z.string().min(1)
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostApiV1CommitmentSessionsResponse = z.union([
    z.object({
        success: z.literal(true),
        data: z.object({
            id: z.uuid(),
            userId: z.uuid(),
            commitmentId: z.uuid(),
            startDate: z.iso.datetime(),
            endDate: z.union([
                z.iso.datetime(),
                z.null()
            ]),
            createdAt: z.iso.datetime(),
            completedAt: z.union([
                z.iso.datetime(),
                z.null()
            ]),
            timezone: z.string(),
            countingDay: z.string(),
            sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
            sessionStatus: z.enum([
                'not_started',
                'in_progress',
                'paused',
                'completed',
                'cancelled'
            ]),
            verificationStatus: z.enum([
                'not_started',
                'pending',
                'failed',
                'succeeded'
            ]),
            sessionGoal: z.enum([
                'steps',
                'miles',
                'screen_time',
                'sleep_time'
            ]),
            actualValue: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            flaggedForReview: z.boolean(),
            fraudDetected: z.boolean(),
            reviewNotes: z.union([
                z.string(),
                z.null()
            ])
        })
    }),
    z.object({
        success: z.literal(true),
        data: z.object({
            id: z.uuid(),
            userId: z.uuid(),
            commitmentId: z.uuid(),
            startDate: z.iso.datetime(),
            endDate: z.union([
                z.iso.datetime(),
                z.null()
            ]),
            createdAt: z.iso.datetime(),
            completedAt: z.union([
                z.iso.datetime(),
                z.null()
            ]),
            timezone: z.string(),
            countingDay: z.string(),
            sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
            sessionStatus: z.enum([
                'not_started',
                'in_progress',
                'paused',
                'completed',
                'cancelled'
            ]),
            verificationStatus: z.enum([
                'not_started',
                'pending',
                'failed',
                'succeeded'
            ]),
            sessionGoal: z.enum([
                'steps',
                'miles',
                'screen_time',
                'sleep_time'
            ]),
            actualValue: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            flaggedForReview: z.boolean(),
            fraudDetected: z.boolean(),
            reviewNotes: z.union([
                z.string(),
                z.null()
            ])
        })
    })
]);

export const zGetApiV1CommitmentSessionsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentSessionsIdResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        userId: z.uuid(),
        commitmentId: z.uuid(),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        createdAt: z.iso.datetime(),
        completedAt: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        timezone: z.string(),
        countingDay: z.string(),
        sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
        sessionStatus: z.enum([
            'not_started',
            'in_progress',
            'paused',
            'completed',
            'cancelled'
        ]),
        verificationStatus: z.enum([
            'not_started',
            'pending',
            'failed',
            'succeeded'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        actualValue: z.union([
            z.number().gte(-140737488355328).lte(140737488355327),
            z.null()
        ]),
        flaggedForReview: z.boolean(),
        fraudDetected: z.boolean(),
        reviewNotes: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zPostApiV1CommitmentSessionsIdCompleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostApiV1CommitmentSessionsIdCompleteResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        userId: z.uuid(),
        commitmentId: z.uuid(),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        createdAt: z.iso.datetime(),
        completedAt: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        timezone: z.string(),
        countingDay: z.string(),
        sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
        sessionStatus: z.enum([
            'not_started',
            'in_progress',
            'paused',
            'completed',
            'cancelled'
        ]),
        verificationStatus: z.enum([
            'not_started',
            'pending',
            'failed',
            'succeeded'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        actualValue: z.union([
            z.number().gte(-140737488355328).lte(140737488355327),
            z.null()
        ]),
        flaggedForReview: z.boolean(),
        fraudDetected: z.boolean(),
        reviewNotes: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zPostApiV1CommitmentSessionsIdCancelData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostApiV1CommitmentSessionsIdCancelResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        userId: z.uuid(),
        commitmentId: z.uuid(),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        createdAt: z.iso.datetime(),
        completedAt: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        timezone: z.string(),
        countingDay: z.string(),
        sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
        sessionStatus: z.enum([
            'not_started',
            'in_progress',
            'paused',
            'completed',
            'cancelled'
        ]),
        verificationStatus: z.enum([
            'not_started',
            'pending',
            'failed',
            'succeeded'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        actualValue: z.union([
            z.number().gte(-140737488355328).lte(140737488355327),
            z.null()
        ]),
        flaggedForReview: z.boolean(),
        fraudDetected: z.boolean(),
        reviewNotes: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zPostApiV1CommitmentSessionsIdPauseData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostApiV1CommitmentSessionsIdPauseResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        userId: z.uuid(),
        commitmentId: z.uuid(),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        createdAt: z.iso.datetime(),
        completedAt: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        timezone: z.string(),
        countingDay: z.string(),
        sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
        sessionStatus: z.enum([
            'not_started',
            'in_progress',
            'paused',
            'completed',
            'cancelled'
        ]),
        verificationStatus: z.enum([
            'not_started',
            'pending',
            'failed',
            'succeeded'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        actualValue: z.union([
            z.number().gte(-140737488355328).lte(140737488355327),
            z.null()
        ]),
        flaggedForReview: z.boolean(),
        fraudDetected: z.boolean(),
        reviewNotes: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zPostApiV1CommitmentSessionsIdResumeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostApiV1CommitmentSessionsIdResumeResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        userId: z.uuid(),
        commitmentId: z.uuid(),
        startDate: z.iso.datetime(),
        endDate: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        createdAt: z.iso.datetime(),
        completedAt: z.union([
            z.iso.datetime(),
            z.null()
        ]),
        timezone: z.string(),
        countingDay: z.string(),
        sessionDuration: z.number().gte(-140737488355328).lte(140737488355327),
        sessionStatus: z.enum([
            'not_started',
            'in_progress',
            'paused',
            'completed',
            'cancelled'
        ]),
        verificationStatus: z.enum([
            'not_started',
            'pending',
            'failed',
            'succeeded'
        ]),
        sessionGoal: z.enum([
            'steps',
            'miles',
            'screen_time',
            'sleep_time'
        ]),
        actualValue: z.union([
            z.number().gte(-140737488355328).lte(140737488355327),
            z.null()
        ]),
        flaggedForReview: z.boolean(),
        fraudDetected: z.boolean(),
        reviewNotes: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zPostApiV1CommitmentSessionsIdVerifyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPostApiV1CommitmentSessionsIdVerifyResponse = z.union([
    z.object({
        success: z.literal(true),
        data: z.string()
    }),
    z.object({
        success: z.literal(true),
        data: z.string()
    })
]);

export const zGetApiV1CommitmentSessionsIdSamplesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1CommitmentSessionsIdSamplesResponse = z.object({
    success: z.literal(true),
    data: z.object({
        motionSamples: z.array(z.object({
            id: z.uuid(),
            commitmentSessionId: z.uuid(),
            capturedAt: z.iso.datetime(),
            intervalMs: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            accelX: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            accelY: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            accelZ: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            accelGX: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            accelGY: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            accelGZ: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            rotAlpha: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            rotBeta: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            rotGamma: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            rotRateAlpha: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            rotRateBeta: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            rotRateGamma: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            orientation: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])
        })),
        gpsSamples: z.array(z.object({
            id: z.uuid(),
            commitmentSessionId: z.uuid(),
            capturedAt: z.iso.datetime(),
            lat: z.number().gte(-140737488355328).lte(140737488355327),
            lng: z.number().gte(-140737488355328).lte(140737488355327),
            speedMps: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            headingDeg: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]),
            horizAcc: z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])
        })),
        pedometerSamples: z.array(z.object({
            id: z.uuid(),
            commitmentSessionId: z.uuid(),
            capturedAt: z.iso.datetime(),
            steps: z.int().gte(-2147483648).lte(2147483647)
        }))
    })
});

export const zPostApiV1CommitmentSessionsIdSamplesData = z.object({
    body: z.optional(z.object({
        motionSamples: z.optional(z.array(z.object({
            capturedAt: z.union([
                z.iso.datetime(),
                z.null()
            ]),
            intervalMs: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            accelX: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            accelY: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            accelZ: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            accelGX: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            accelGY: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            accelGZ: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            rotAlpha: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            rotBeta: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            rotGamma: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            rotRateAlpha: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            rotRateBeta: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            rotRateGamma: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            orientation: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]))
        }))).default([]),
        gpsSamples: z.optional(z.array(z.object({
            capturedAt: z.union([
                z.iso.datetime(),
                z.null()
            ]),
            lat: z.number().gte(-140737488355328).lte(140737488355327),
            lng: z.number().gte(-140737488355328).lte(140737488355327),
            speedMps: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            headingDeg: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ])),
            horizAcc: z.optional(z.union([
                z.number().gte(-140737488355328).lte(140737488355327),
                z.null()
            ]))
        }))).default([]),
        pedometerSamples: z.optional(z.array(z.object({
            capturedAt: z.union([
                z.iso.datetime(),
                z.null()
            ]),
            steps: z.int().gte(-2147483648).lte(2147483647)
        }))).default([])
    })),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPostApiV1CommitmentSessionsIdSamplesResponse = z.union([
    z.object({
        success: z.literal(true),
        data: z.object({
            motionSamplesInserted: z.number(),
            gpsSamplesInserted: z.number(),
            pedometerSamplesInserted: z.number()
        })
    }),
    z.object({
        success: z.literal(true),
        data: z.object({
            motionSamplesInserted: z.number(),
            gpsSamplesInserted: z.number(),
            pedometerSamplesInserted: z.number()
        })
    })
]);

export const zPostApiV1PaymentsData = z.object({
    body: z.optional(z.object({
        name: z.optional(z.string()),
        phone: z.optional(z.string()),
        email: z.optional(z.email()),
        metadata: z.optional(z.record(z.string(), z.string())),
        amount: z.int().gt(0),
        currency: z.string().length(3),
        paymentMethodId: z.string().min(1),
        commitmentId: z.uuid()
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostApiV1PaymentsResponse = z.object({
    success: z.literal(true),
    data: z.object({
        paymentIntentId: z.string(),
        clientSecret: z.string(),
        customerSessionClientSecret: z.string(),
        customerId: z.string(),
        publishableKey: z.string()
    })
});

export const zPostApiV1PaymentsConfirmData = z.object({
    body: z.optional(z.object({
        paymentIntentId: z.string().min(1)
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostApiV1PaymentsConfirmResponse = z.object({
    success: z.literal(true),
    data: z.object({
        status: z.string()
    })
});

export const zGetApiV1PoolData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetApiV1PoolResponse = z.object({
    success: z.literal(true),
    data: z.object({
        id: z.uuid(),
        stakesHeld: z.number().gte(-140737488355328).lte(140737488355327),
        balance: z.number().gte(-140737488355328).lte(140737488355327),
        totalRakeCollected: z.number().gte(-140737488355328).lte(140737488355327),
        createdAt: z.iso.datetime(),
        updatedAt: z.iso.datetime()
    })
});

export const zPostWebhookPaymentsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostCronForfeitExpiredData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPostCronForfeitExpiredResponse = z.object({
    success: z.literal(true),
    data: z.object({
        forfeitedCount: z.number(),
        commitments: z.array(z.object({
            commitmentId: z.uuid(),
            userId: z.uuid(),
            stakeAmount: z.number(),
            sessionsCompleted: z.number(),
            sessionsRequired: z.number()
        }))
    })
});
